Add styled-components
This commit causes tsc to fail with "node_modules/styled-components/typings/styled-components.d.ts(116,44): error TS2503: Cannot find namespace 'NodeJS'."